#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# npm test
# npx --no-install commitlint --edit "$1"
npx commitlint --edit "${1}"

# npx husky add .husky/commit-msg "npx --no-install commitlint -e $HUSKY_GIT_PARAMS"

# npx --no-install commitlint -e $HUSKY_GIT_PARAMS
