name: Production workflow

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'dist/upx/**'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: npm install
      - run: npm run lint
      - run: npm run build --if-present

  build:
    runs-on: ubuntu-latest

    steps:
      - run: npm run build --if-present

      # - name: Deploy to netlify
      #   uses: netlify/actions/cli@master
      #   with:
      #     args: deploy --dir=dist --prod
      #   env:
      #     NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      #     NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}


# Webpack reference
# name: NodeJS with vite

# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         node-version: [14.x, 16.x, 18.x]

#     steps:
#     - uses: actions/checkout@v3

#     - name: Use Node.js ${{ matrix.node-version }}
#       uses: actions/setup-node@v3
#       with:
#         node-version: ${{ matrix.node-version }}

#     - name: Build
#       run: |
#         npm install
#         npx run build
